#!/bin/sh

echo "🔍 Verificando archivos antes del commit..."

# Formatear código con Prettier
echo "🚀 Ejecutando Prettier..."
if ! yarn prettier . --write; then
  echo "❌ Error al ejecutar Prettier."
  exit 1
fi

# Agregar los archivos modificados después del formateo
git add .

# Verificar que el código esté actualizado antes del push
echo "🔄 Verificando que tu código esté actualizado..."
if ! git pull; then
  echo "❌ Error al actualizar el código. Revisa los conflictos."
  exit 1
fi

echo "✅ Todo listo para el commit. 🎉"
